/**
 * Visual signatures — one vision call per image, for visual discovery.
 *
 * ── WHY THIS REPLACES THREE CALLS WITH ONE ──────────────────────────────────
 * The pipeline used to make three round trips per image: alt text
 * (attributes.ts), attributes (attributes.ts), and — separately, from a
 * different admin route — region detection (regions.ts). Every one of them
 * asks the same model to look at the same photograph. This asks once and
 * returns all of it, which is both cheaper and internally consistent: the
 * scene summary, the alt text and the object list now describe the same
 * reading of the image rather than three independent ones that can disagree.
 *
 * ── WHAT A "SIGNATURE" IS, AND WHY IT IS TEXT ───────────────────────────────
 * A signature is a dense, deliberately un-poetic description of how something
 * LOOKS: form, silhouette, material, finish, palette, design language, period.
 * It is written to be embedded, not to be read by a human, and it is never
 * rendered anywhere in the product.
 *
 * It is text because it has to be. The only embedding provider this app has a
 * key for is OpenAI, and OpenAI has no image-embedding endpoint — so a true
 * CLIP-style pixel embedding would mean a new vendor, a new secret, and a
 * vector of a different width (512 or 768) that could not go in the existing
 * `image_ai.embedding vector(1536)` column behind the existing HNSW indexes.
 * That is a parallel embedding system, which is precisely the failure this
 * codebase keeps having. A structured visual description embedded into the
 * column that already exists reuses the whole retrieval stack unchanged.
 *
 * The honest tradeoff: two objects described alike will collide even if their
 * surfaces differ, and fine texture is lost. Mitigated by making the
 * description structured and specific, and by constraining retrieval with
 * taxonomy. See lib/discovery/visualDiscovery.ts.
 *
 * ── THIS IS NOT THE ALT-TEXT EMBEDDING ──────────────────────────────────────
 * image_ai.embedding previously held an embedding of the SEO alt sentence
 * ("Interior view of a living room with large windows"), and for 85% of rows
 * not even that — a sine wave derived from the URL string, generated by
 * getImageEmbedding's fallback and indistinguishable from noise. Both are
 * replaced here. See the note in embedding.ts.
 */

/** Object types worth detecting. The stored `object_type` vocabulary. */
export const VALID_OBJECT_TYPES = new Set([
  "seating",    // sofa, chair, stool, bench, armchair
  "table",      // dining table, coffee table, side table, desk
  "lighting",   // pendant, floor lamp, table lamp, sconce, chandelier
  "bed",        // bed frame, headboard
  "sink",       // bathroom basin, kitchen sink
  "faucet",     // tap, mixer
  "rug",        // rug, carpet, mat
  "shelving",   // shelf, bookcase, wall unit, cabinet, storage
]);

export interface DetectedObject {
  label: string;
  object_type: string;
  keywords: string[];
  confidence: number;
  /** Centre and box as percentages of the image, 0–100. Never pixels. */
  x: number;
  y: number;
  width: number;
  height: number;
  /** Dense visual description of THIS object, for embedding. Never displayed. */
  signature: string;
}

export interface VisualSignature {
  /** One human-readable sentence. Becomes listing_images.alt. */
  alt: string;
  /** Dense visual description of the whole frame, for embedding. */
  signature: string;
  /** Short scene note stored on image_regions.scene_summary. */
  scene_summary: string;
  /** category / material / color / context — image_ai.attrs. */
  attrs: {
    category: string[];
    material: string[];
    color: string[];
    context: string[];
  };
  /** 0–100. */
  confidence: number;
  /** Empty for product photography; populated for project scenes. */
  objects: DetectedObject[];
  error?: string;
}

const MAX_OBJECTS = 6;

/**
 * ── MODEL AND DETAIL, CHOSEN BY MEASUREMENT ─────────────────────────────────
 * Both were first set to gpt-4o-mini at detail "low" on the assumption that a
 * bounding box only has to be good enough to say which object a click landed
 * on. Measured on two live project photographs, that assumption was wrong in
 * the way that matters: mini/low does not localise at all. Every object came
 * back centred — three objects at x=50 on an image with a table left, chairs
 * middle and a sink right — so every box overlapped and a click could not have
 * distinguished them. It also ignored the stated 0–100 scale and returned
 * fractions.
 *
 *   image 574aa0fa        objects returned as (x,y)
 *   gpt-4o-mini / low     table(0.5,0.5) seating(0.5,0.5) lighting(0.5,0.2) sink(0.8,0.5)
 *   gpt-4o-mini / high    table(30,50) seating(25,50) seating(35,50) seating(45,50) sink(80,50)
 *   gpt-4o     / high     seating(30,60) seating(50,60) seating(70,60) table(50,50) faucet(85,50)
 *
 * The surprise was the price. gpt-4o-mini bills images through a much larger
 * token multiplier: the same photograph at detail "high" cost 37,013 input
 * tokens on mini and 1,283 on gpt-4o. At list prices those come to $0.0056 and
 * $0.0052 per image. gpt-4o localises better for the same money, so project
 * photographs use it.
 *
 * Product photographs need no coordinates at all — one object, already the
 * subject of the page — so they stay on mini at "low", about $0.0006 each,
 * roughly a tenth of the cost.
 */
const MODEL_BY_KIND = {
  /** Localisation matters; gpt-4o is both better and no more expensive here. */
  project: { model: "gpt-4o", detail: "high" as const },
  /** No coordinates required, so the cheap path is the right one. */
  product: { model: "gpt-4o-mini", detail: "low" as const },
};
function systemPrompt(kind: "project" | "product"): string {
  const shared = `You describe architectural and interior photographs for a visual search index.

Write descriptions that are VISUAL and CONCRETE. Name form, silhouette, proportion, material, finish, colour, and design language (e.g. "tubular chrome cantilever frame, tan saddle leather sling seat, Bauhaus"). Never write mood, marketing or interpretation ("inviting", "stunning", "perfect for"). Never mention the photograph, the lighting setup, or the viewer.

Return JSON only.`;

  if (kind === "product") {
    return `${shared}

This is a PRODUCT photograph. Describe the product itself.

Schema:
{
  "alt": "One plain sentence, 80-180 characters, describing the object factually.",
  "signature": "40-70 words. Object type, silhouette, structure, materials, finish, colour palette, proportions, distinguishing details, design language and period.",
  "scene_summary": "One short clause describing the setting, or an empty string for a plain studio background.",
  "attrs": {
    "category": ["lowercase object category terms"],
    "material": ["lowercase materials"],
    "color": ["lowercase colours"],
    "context": ["lowercase setting or room terms, may be empty"]
  },
  "confidence": 0-100,
  "objects": []
}`;
  }

  return `${shared}

This is an ARCHITECTURAL PROJECT photograph. Describe the space, then locate the purchasable objects in it.

For "objects": return at most ${MAX_OBJECTS} objects that a designer could actually specify and buy. Ignore walls, floors, ceilings, windows, doors, joinery, plants, artwork, books and people. Only return an object if you can see it well enough to describe it. Confidence below 0.6 means leave it out.

object_type must be exactly one of: seating, table, lighting, bed, sink, faucet, rug, shelving.

Coordinates are PERCENTAGES of the full image, 0-100 — never fractions of 1. x and y are the CENTRE of the object; width and height are its bounding box.

Look carefully at WHERE each object actually sits in the frame. An object against the left edge has a small x; one against the right edge has a large x; one high in the frame has a small y. Objects at different places must get different coordinates. Do not centre everything. These numbers decide what a click selects, so a centred guess is worse than a rough but honest position.

Schema:
{
  "alt": "One plain sentence, 80-180 characters, describing the space factually.",
  "signature": "40-70 words. Room type, spatial character, palette, dominant materials and finishes, quality of light, furniture idiom, design language and period.",
  "scene_summary": "One short sentence describing the space.",
  "attrs": {
    "category": ["lowercase object categories present"],
    "material": ["lowercase materials"],
    "color": ["lowercase colours"],
    "context": ["lowercase room or setting terms"]
  },
  "confidence": 0-100,
  "objects": [
    {
      "label": "curved modular sofa",
      "object_type": "seating",
      "keywords": ["curved", "modular", "boucle", "low-profile"],
      "confidence": 0.93,
      "x": 45, "y": 65, "width": 30, "height": 20,
      "signature": "25-45 words describing ONLY this object: silhouette, frame, upholstery or material, finish, colour, proportions, design language."
    }
  ]
}`;
}

const EMPTY: VisualSignature = {
  alt: "",
  signature: "",
  scene_summary: "",
  attrs: { category: [], material: [], color: [], context: [] },
  confidence: 0,
  objects: [],
};

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

function strArray(v: unknown, cap = 12): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((x): x is string => typeof x === "string")
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean)
    .slice(0, cap);
}

function clampPct(v: unknown, fallback: number): number {
  const n = Number(v);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(0, Math.min(100, n));
}

/**
 * Describe one image. Returns EMPTY with an `error` rather than throwing, so a
 * batch run over a thousand images is never ended by one unreadable file.
 */
export async function describeImageVisually(
  imageUrl: string,
  kind: "project" | "product",
  { retries = 2 }: { retries?: number } = {}
): Promise<VisualSignature> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey?.trim()) return { ...EMPTY, error: "OPENAI_API_KEY not set" };

  const url = typeof imageUrl === "string" ? imageUrl.trim() : "";
  if (!url) return { ...EMPTY, error: "imageUrl empty" };

  let lastError = "";
  for (let attempt = 0; attempt <= retries; attempt++) {
    if (attempt > 0) await sleep(1000 * 2 ** (attempt - 1));

    let res: Response;
    try {
      res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model: MODEL_BY_KIND[kind].model,
          max_tokens: 1400,
          temperature: 0.2,
          response_format: { type: "json_object" },
          messages: [
            { role: "system", content: systemPrompt(kind) },
            {
              role: "user",
              content: [
                { type: "image_url", image_url: { url, detail: MODEL_BY_KIND[kind].detail } },
              ],
            },
          ],
        }),
      });
    } catch (e) {
      lastError = e instanceof Error ? e.message : String(e);
      continue;
    }

    if (!res.ok) {
      lastError = `OpenAI ${res.status}: ${(await res.text()).slice(0, 200)}`;
      // 4xx other than rate limiting will not succeed on a retry.
      if (res.status !== 429 && res.status < 500) break;
      continue;
    }

    const data = (await res.json()) as { choices?: { message?: { content?: string } }[] };
    const raw = (data.choices?.[0]?.message?.content ?? "").trim();
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(raw) as Record<string, unknown>;
    } catch {
      lastError = `unparseable response: ${raw.slice(0, 120)}`;
      continue;
    }

    return normalize(parsed, kind);
  }

  return { ...EMPTY, error: lastError || "unknown failure" };
}

function normalize(parsed: Record<string, unknown>, kind: "project" | "product"): VisualSignature {
  const attrsRaw = (parsed.attrs ?? {}) as Record<string, unknown>;

  const rawObjects =
    kind === "product"
      ? []
      : (Array.isArray(parsed.objects) ? parsed.objects : [])
          .map((o) => o as Record<string, unknown>)
          .filter((o) => VALID_OBJECT_TYPES.has(String(o.object_type ?? "")))
          .filter((o) => Number(o.confidence) >= 0.6);

  /*
   * Percentages or fractions?
   *
   * The prompt asks for 0–100 and says so twice, and the model still sometimes
   * answers in fractions of 1 — observed on gpt-4o-mini, where a whole frame
   * came back as x=0.5, y=0.5, width=0.4. Taken literally that is a box four
   * tenths of one percent wide in the top-left corner: invisible, unclickable,
   * and indistinguishable from a genuine object at the frame's edge.
   *
   * So the scale is inferred from the answer rather than trusted. If nothing
   * in the whole response exceeds 1, it is a fraction response and everything
   * is multiplied up. A real percentage response cannot look like this — a set
   * of objects that all sit within the top-left 1% of an image is not a
   * photograph anyone published.
   */
  const allCoords = rawObjects.flatMap((o) => [Number(o.x), Number(o.y), Number(o.width), Number(o.height)]).filter((n) => Number.isFinite(n));
  const scale = allCoords.length > 0 && allCoords.every((n) => n <= 1) ? 100 : 1;

  const objects: DetectedObject[] =
    rawObjects
          .map((o) => ({
            label: String(o.label ?? "").trim() || String(o.object_type),
            object_type: String(o.object_type),
            keywords: strArray(o.keywords, 8),
            confidence: Math.max(0, Math.min(1, Number(o.confidence) || 0)),
            x: clampPct(Number(o.x) * scale, 50),
            y: clampPct(Number(o.y) * scale, 50),
            /* A zero-width box can never contain a click. Anything the model
               leaves out or returns as 0 gets a small but real default, so the
               object stays selectable rather than becoming dead pixels. */
            width: Math.max(4, clampPct(Number(o.width) * scale, 12)),
            height: Math.max(4, clampPct(Number(o.height) * scale, 12)),
            signature: String(o.signature ?? "").trim(),
          }))
          .slice(0, MAX_OBJECTS);

  return {
    alt: String(parsed.alt ?? "").trim(),
    signature: String(parsed.signature ?? "").trim(),
    scene_summary: String(parsed.scene_summary ?? "").trim(),
    attrs: {
      category: strArray(attrsRaw.category),
      material: strArray(attrsRaw.material),
      color: strArray(attrsRaw.color),
      context: strArray(attrsRaw.context),
    },
    confidence: Math.max(0, Math.min(100, Number(parsed.confidence) || 0)),
    objects,
  };
}
